version: "3.9"
services:
  app:
    build: .
    restart: on-failure
    environment:
      - MONGODB_URL=mongodb://admin:admin@mongodb:27017
      - MASTER_KEYS=ashfojhuihgusAIOGUHJOIUSADGHjoSDgj, hdashfuiahfuiashfuiashfuias, fhuiahfuiahfuia
      - JWT_SECRET=dsafasfadfadsfdsafdsfdsfdssdfdsfdsf
      - JWT_EXPIRATION=24h
      - APP_PORT=8080
    ports:
      - '8080:8080'
    depends_on:
      - mongodb
    networks:
      - placesapi

  mongodb:
    image: mongo
    restart: on-failure
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    expose:
      - 27017
    ports:
      - '27017:27017'
    volumes:
      - mongodb-data:/data/db
    networks:
      - placesapi

  mongo-express:
    image: mongo-express
    restart: on-failure
    ports:
      - '8081:8081'
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
      ME_CONFIG_MONGODB_URL: mongodb://admin:admin@mongodb:27017/
      ME_CONFIG_BASICAUTH: true
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
    depends_on:
      - mongodb
    networks:
      - placesapi

networks:
  placesapi:
    name: placesapi
    driver: bridge

volumes:
  mongodb-data:
    name: mongodb-data
    driver: local